services:
  # FRONTEND
  - type: web
    name: medmetrics-frontend
    runtime: node
    repo: https://github.com/AmandaNick85/MedMetrics.git

    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend

    envVars:
      - key: VITE_API_AUTH_URL
        fromService:
          type: web
          name: medmetrics-auth-service
          property: url

      - key: VITE_API_ANALYTICS_URL
        fromService:
          type: web
          name: medmetrics-analytics-service
          property: url

  # AUTH SERVICE
  - type: web
    name: medmetrics-auth-service
    runtime: node
    plan: free
    repo: https://github.com/AmandaNick85/MedMetrics.git

    buildCommand: cd auth-service && npm install
    startCommand: cd auth-service && npm start

    envVars:
      - key: PORT
        value: 3001

      - key: DATABASE_URL
        sync: false

      - key: JWT_SECRET
        generateValue: true

  # ANALYTICS SERVICE
  - type: web
    name: medmetrics-analytics-service
    runtime: docker
    plan: free
    repo: https://github.com/AmandaNick85/MedMetrics.git

    dockerfilePath: ./analytics-service/Dockerfile

    envVars:
      - key: PORT
        value: 3002

      - key: MONGO_URI
        sync: false

      - key: JWT_SECRET
        generateValue: true