services:
  # 1. FRONTEND (Site Estático)
  - type: static
    name: medmetrics-frontend
    runtime: node
    repo: https://github.com/AmandaNick85/MedMetrics.git
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist # Caminho físico correto a partir da raiz

    envVars:
      - key: VITE_API_AUTH_URL
        fromService:
          type: web
          name: medmetrics-auth-service
          property: host

      - key: VITE_API_ANALYTICS_URL
        fromService:
          type: web
          name: medmetrics-analytics-service
          property: host

  # 2. AUTH SERVICE (API Node)
  # Exported from Render on 2026-06-17T18:42:20Z
version: "1"
projects:
- name: MedMetrics
  environments:
  - name: Production
    services:
    - type: web
      name: auth-service
      runtime: node
      repo: https://github.com/AmandaNick85/MedMetrics
      plan: free
      envVars:
      - key: DATABASE_URL
        sync: false
      region: oregon
      buildCommand: yarn install
      startCommand: node src/server.js
      autoDeployTrigger: commit
      rootDir: MedMetrics/auth-service


  # 3. ANALYTICS SERVICE (Sua API Dockerizada)
  - type: web
    name: medmetrics-analytics-service
    runtime: docker
    plan: free
    repo: https://github.com/AmandaNick85/MedMetrics.git
    dockerfilePath: ./analytics-service/Dockerfile # O Render lê o Dockerfile diretamente aqui
    dockerContext: ./analytics-service # Define a pasta do microsserviço como o contexto do Docker
    envVars:
      - key: PORT
        value: 3002
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true